### PR TITLE
use caldera forms render form method

### PR DESCRIPTION
**Pull request by Desertsnowman**

### CODE REVIEW

**Comment by nandotess** [comment]
@Desertsnowman please, fix the issue with the WordPress escaping function alerted by Travis-CI:
screen shot 2017-05-02 at 11 02 11
Thanks.

**Comment by nandotess** [comment]
@Desertsnowman I suggest you test with `wp_kses_post` because probably this function will display complex HTML.

**Comment by Desertsnowman** [comment]
@nandotess I got the same note while editing it: 
phpcs-lsx

My concern is that the function may already have sanitisation and also could also remove vital code that is not allowed in normal post HTML.

However, it's your call.

**Comment by Desertsnowman** [comment]
@nandotess added.

**Pull request merged**
